#BEGIN: [Wed Sep  6 00:15:40 2023]
#HOST: s11
#TIMELIMIT: 1800
#MEMLIMIT: 0
#SOLVER: existent-cpu-suisen-cp2
#INSTANCE1: /benchmark/random_instance/random_instance033_graph004.col
#INSTANCE2: /benchmark/random_instance/random_instance033_graph004_01.dat
#COMMAND: docker run --cidfile /tmp/cid.txt --init --rm -t --ulimit cpu=1800 -v /home/share/benchmark/ISR-benchmark:/benchmark suisen-cp2 /benchmark/random_instance/random_instance033_graph004.col /benchmark/random_instance/random_instance033_graph004_01.dat
[36m15:15:46 [INFO] Time reorder   : 6 (sec)[0m
Traceback (most recent call last):
  File "/solver-dir/./Main.py", line 174, in <module>
    solve(
  File "/solver-dir/./Main.py", line 77, in solve
    source = [mapping[u] for u in source]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/solver-dir/./Main.py", line 77, in <listcomp>
    source = [mapping[u] for u in source]
              ~~~~~~~^^^
KeyError: 428
Command exited with non-zero status 1
	Command being timed: "bash /solver-dir/run.sh /benchmark/random_instance/random_instance033_graph004.col /benchmark/random_instance/random_instance033_graph004_01.dat"
	User time (seconds): 6.32
	System time (seconds): 0.03
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:06.35
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 51368
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 15428
	Voluntary context switches: 15
	Involuntary context switches: 17
	Swaps: 0
	File system inputs: 0
	File system outputs: 32
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
#END: [Wed Sep  6 00:15:46 2023]
